#!/bin/bash

#Store Systems IP
#/sbin/ifconfig eht0* | grep 'inet addr:' | cut -d: -f2 | awk '{ print $1}'

sysIP="$(hostname -I | awk '{print $1}')"

echo "$sysIP" >> /etc/trustedIPs.conf

#Network Traffic Interface
eth="$(ifconfig | head -n 1 | awk '{print $1}')"
echo "$eth"

gcc /etc/daemontest.c -o /etc/detectionD
/etc/detectionD

#sudo tcpdump -s 65535 -w log
